### ISSUE TITLE
Taggd is not a constructor

### ISSUE THREAD

**Issue by ifalldev** [timseverien/taggd#52] opened 2017-01-19 03:23 UTC
Hi, I'm trying to use the package through **NPM** on **MeteorJS** but I'm facing a strange issue.

 My implementation:

`npm install --save taggd`

and so

```
import Taggd from 'taggd';

const img = document.querySelector('#myImage');
const taggd = new Taggd(img);
```

But when I run the application this error appears on my console: `Uncaught TypeError: Taggd is not a constructor`.

And if i print a log on my console before the `new Taggd` (like this console.log(Taggd)) the result is a empty object! 

But if I try to access the Taggd constructor on the console (just after the error has appeared) the return is the constructor function! _And I can do all of my implementation there!_

I would appreciate some help!

Thank you!

**Comment by timseverien** [comment] 2017-01-19 06:12
Huh, interesting. This will be fun to debug! I’m assuming that the error
occurs in a scoped context. By logging Taggd in the console manually, you
refer to the global Taggd constructor. So I think the module isn’t exported
correctly, but Taggd is defined globally.

Could you please provide some additional information?

- What version of what ES6 transpiler do you use?
- Can you provide a script, just so I’m sure I’m reproducing it correctly?

You should be able to resume work if you import it like so:

```
import 'taggd';
```

Note this is a temporary fix until I find and solve the bug :)

Thanks!

Op do 19 jan. 2017 04:23 schreef Caio Batista <notifications@github.com>:

**Comment by ifalldev** [comment] 2017-01-19 09:06
Yeah! It works with `import 'taggd'` - I'm trying figure it out why.

I'm using babel-compiler@6.13.0.

My script is just that which I passed before.

I installed it with node, import the package and tried to use it on MeteorJS 1.4.2.
(If I'm not seeing what you need about my script, show me please)

Thank you!

**Comment by timseverien** [comment] 2017-02-01 20:22
Ugh, having issues fixing this. Apparently, ES2015-style imports expects a format that is achieved by exporting ES2015-style.

Unfortunately, this affects AMD imports and the global “export” as well.

Apparently, a `module` field in `package.json` is semi-standardised across different bundlers, allowing you to specify a path to a ES2015 file.

Would you please be so kind to test this change?

```shell
npm install timseverien/taggd#es2015-import
```

**Comment by sharpner** [comment] 2017-02-02 09:27
I am running into the same issue. So maybe some feedback helps:
I am currently testing with the es2015-import branch and it helps a bit.

This works: 
```
import Taggd from 'Taggd';
import {Tag} from 'Taggd';
```

but what I would need:
```
import {Tag, Taggd} from 'Taggd';
```
does not work. 

Hope it helps and thx for fixing this :-)

**Comment by timseverien** [comment] 2017-02-02 10:29
Good point. I might have an idea to solve it, but I'll have to look into it. Thanks for trying it out :)

**Comment by timseverien** [comment] 2017-02-06 20:20
I’ve made two files, each exporting the library differently.

- `umd.js` exports `Taggd`, and the `Tag` class can be found as a static field in `Taggd`.
-  `modern.js` export exports `Taggd` and `Tag` as named exports.

This means that those who import Taggd via ES2015 imports get access to both `Taggd` and `Tag` separately, whereas those who use the UMD bundle get access to the `Taggd` class and will have to use `Taggd.Tag` to create tags. This is slightly inconvenient, but I’m hoping this makes Taggd compatible for both import strategies.

To clarify this, I have added a section on the `README`.

Can either @ifalldev or @sharpner check whether Taggd imports as expected for an ES2015+ codebase? Again, you can fetch the branch using `npm install timseverien/taggd#es2015-import`. Make sure it installs the latest version of that branch instead of fetching it from cache or anything.

If all looks well, I’m going to merge the branch, release a new major and close this issue :)

**Comment by sharpner** [comment] 2017-02-07 17:03
hey thanks for the fast updates. 

I just did a quick check with webpack and `import Taggd, {Tag} from 'taggd';` works for me now!

**Comment by sharpner** [comment] 2017-02-16 09:55
are you going to merge this anytime soon? :)

**Comment by timseverien** [comment] 2017-02-23 13:40
I might do it this weekend. I have had like 0 spare time past two weeks 😑

**Comment by sharpner** [comment] 2017-02-23 14:24
yeah no worries :-) thanks for the update

**Comment by timseverien** [comment] 2017-03-02 18:57
I forgot to say: it’s merged in 4.0.0 now :)

**Closed by timseverien** 2017-03-02 18:57 UTC

**Comment by sharpner** [comment] 2017-03-03 08:08
thx :)

**Comment by ifalldev** [comment] 2017-05-29 14:18
Hey! Sorry for my late feedback!

Everything went fine for me using `import` syntax in 4.0.0. Thanks for this!
